# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty
relative_permalinks: true

# Setup
title:            Jekyll / Foundation 6
tagline:          'A Jekyll starter project'
description:      'Observations from the East Riding of Yorkshire'
url:              http://localhost
baseurl:          /
source:           ./src
exclude:          [assets]
destination:      ./dist
keep_files:       [assets]

author:
  name:           'Richard Tugwell'

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Richardtugwell/foundation-blog-jekyll
