# Dependencies
markdown:         redcarpet
highlighter:      pygments
gems:
  - jekyll-archives
  - redcarpet
  - jekyll-paginate

# Permalinks
permalink:        none

# Setup
title:            The Blog
tagline:          'A Jekyll / Foundation 6 starter project'
description:      'Observations from the East Riding of Yorkshire'
url:              http://localhost
baseurl:          /
source:           ./src
exclude:          [assets]
destination:      ./dist
keep_files:       [assets]

# Archives
jekyll-archives:
  enabled: [tags,categories,year,month]
  layout: 'archive'
  permalinks:
    year: '/:year/'
    month: '/:year/:month/'
    day: '/:year/:month/:day/'
    tag: '/tag/:name/'
    category: '/category/:name/'


author:
  name:           'Richard Tugwell'

paginate:         5

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/Richardtugwell/foundation-blog-jekyll
